# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="sauron"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="A frame tracking events inside and outside your emacs buffers"

HOMEPAGE="https://github.com/djcb/sauron"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
