# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="verdict"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Generic test runner with treemacs results UI"

HOMEPAGE="https://github.com/tjarvstrand/verdict.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/treemacs
	app-emacs/dash"
RDEPEND="app-emacs/treemacs
	app-emacs/dash"
