# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="elsqlite"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="SQLite browser"

HOMEPAGE="https://github.com/dusanx/elsqlite"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
