# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="ob-agent-shell"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Org-babel backend for agent-shell"

HOMEPAGE="https://github.com/eddof13/ob-agent-shell"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/agent-shell
	app-emacs/org-mode"
RDEPEND="app-emacs/agent-shell
	app-emacs/org-mode"
