# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="citar-typst"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Typst support for citar"

HOMEPAGE="https://codeberg.org/ashton314/citar-typst"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/citar"
RDEPEND="app-emacs/citar"
