# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="agent-shell-math-renderer"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Display-math rendering for agent-shell"

HOMEPAGE="https://github.com/alberti42/agent-shell-math-renderer"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/agent-shell
	app-emacs/latex-to-svg-backend"
RDEPEND="app-emacs/agent-shell
	app-emacs/latex-to-svg-backend"
