# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="org-people"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Work with a contact-list in org-mode files"

HOMEPAGE="https://github.com/skx/org-people"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/org-mode"
RDEPEND="app-emacs/org-mode"
