# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="elixir-iex"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="IEx REPL via eat terminal emulator"

HOMEPAGE="https://github.com/mojochao/elixir-iex"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/eat"
RDEPEND="app-emacs/eat"
