# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="elfeed-ai"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="AI-powered article summarization for elfeed"

HOMEPAGE="https://github.com/danielfleischer/elfeed-ai"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/elfeed
	app-emacs/gptel"
RDEPEND="app-emacs/elfeed
	app-emacs/gptel"
