# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="oai"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="AI-LLM chat blocks for org-mode"

HOMEPAGE="https://github.com/Anoncheg1/emacs-oai"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
