# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="python-unicode-escape"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Completion for Python \\N{NAME} escapes"

HOMEPAGE="https://github.com/jb3/python-unicode-escape"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
