# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="ai-code"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Unified interface for AI coding backends such as Claude Code, Codex CLI, Gemini CLI, Copilot CLI, Opencode, Grok CLI, Aider CLI, etc"

HOMEPAGE="https://github.com/tninja/ai-code-interface.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/transient
	app-emacs/magit"
RDEPEND="app-emacs/transient
	app-emacs/magit"
