# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="bluesky"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="A Bluesky client"

HOMEPAGE="https://github.com/ahyatt/emacs-bluesky"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/plz
	app-emacs/futur
	app-emacs/vui"
RDEPEND="app-emacs/plz
	app-emacs/futur
	app-emacs/vui"
