# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="doxymin"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Create doxygen style docs the easy way"

HOMEPAGE="https://gitlab.com/L0ren2/doxymin"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
