# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="pimacs"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Emacs Client for Pi"

HOMEPAGE="https://github.com/ananthakumaran/pimacs.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/compat
	app-emacs/markdown-mode
	app-emacs/timeout
	app-emacs/pcre2el
	app-emacs/spinner
	app-emacs/transient"
RDEPEND="app-emacs/compat
	app-emacs/markdown-mode
	app-emacs/timeout
	app-emacs/pcre2el
	app-emacs/spinner
	app-emacs/transient"
