# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="eager-state"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Eagerly persist data onto disk"

HOMEPAGE="https://github.com/meedstrom/eager-state"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/llama"
RDEPEND="app-emacs/llama"
