# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="cui"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Chat blocks in org-mode for LLM and agents"

HOMEPAGE="https://codeberg.org/Anoncheg/emacs-cui"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
