# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="floobits"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Floobits plugin for real-time collaborative editing"

HOMEPAGE="https://stable.melpa.org/packages/"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/json
	app-emacs/highlight"
RDEPEND="app-emacs/json
	app-emacs/highlight"
