# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="mu4e-autotask"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Email automation for mu4e"

HOMEPAGE="https://github.com/laurynas-biveinis/mu4e-autotask"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
