# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="kirigami"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="A unified method to fold and unfold text"

HOMEPAGE="https://github.com/jamescherti/kirigami.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
