# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="mu4e-llm"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="AI-powered email assistance for mu4e"

HOMEPAGE="https://github.com/sillyfellow/mu4e-llm"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/llm"
RDEPEND="app-emacs/llm"
