# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="single"
REALNAME="orglink"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="use Org Mode links in other modes"

HOMEPAGE="https://stable.melpa.org/packages/"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/org
	app-emacs/seq"
RDEPEND="app-emacs/org
	app-emacs/seq"
