# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="shannon-max"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Analyze your keybindings with information theory"

HOMEPAGE="https://github.com/sstraust/shannonmax"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
