# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="ekg"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="A sqlite-based note-taking package based on tags"

HOMEPAGE="https://github.com/ahyatt/ekg"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/triples
	app-emacs/llm
	app-emacs/vui"
RDEPEND="app-emacs/triples
	app-emacs/llm
	app-emacs/vui"
