# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="auto-side-windows"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Simplified buffer management for side windows"

HOMEPAGE="https://github.com/MArpogaus/auto-side-windows"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
