# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="bitbucket-devops"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Bitbucket Cloud DevOps workflows"

HOMEPAGE="https://github.com/will-abb/bitbucket-devops.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/magit
	app-emacs/markdown-mode
	app-emacs/transient
	app-emacs/yaml"
RDEPEND="app-emacs/magit
	app-emacs/markdown-mode
	app-emacs/transient
	app-emacs/yaml"
