# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="pi-coding-agent"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Emacs frontend for pi coding agent"

HOMEPAGE="https://github.com/dnouri/pi-coding-agent"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/markdown-mode
	app-emacs/transient"
RDEPEND="app-emacs/markdown-mode
	app-emacs/transient"
