# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="duckdb-query"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="DuckDB query results as native Elisp data structures"

HOMEPAGE="https://github.com/gggion/duckdb-query.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
