# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="latex-to-svg-backend"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="LaTeX-to-SVG rendering engine with caching"

HOMEPAGE="https://github.com/alberti42/latex-to-svg-backend"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
