# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="hel"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Helix Emulation Layer"

HOMEPAGE="https://github.com/helheim-emacs/hel"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/dash
	app-emacs/avy
	app-emacs/pcre2el
	app-emacs/ultra-scroll"
RDEPEND="app-emacs/dash
	app-emacs/avy
	app-emacs/pcre2el
	app-emacs/ultra-scroll"
