# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="magit-standup"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Collect recent git commits for standup notes"

HOMEPAGE="https://github.com/function-artisans/magit-standup"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/magit
	app-emacs/transient"
RDEPEND="app-emacs/magit
	app-emacs/transient"
