# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="pathaction"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Execute the pathaction.yaml rules from your editor"

HOMEPAGE="https://github.com/jamescherti/pathaction.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
