# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="gptel-agent-harness"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Agent execution harness for gptel-agent"

HOMEPAGE="https://github.com/beacoder/gptel-agent-harness"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/compat
	app-emacs/gptel-agent"
RDEPEND="app-emacs/compat
	app-emacs/gptel-agent"
