# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="eselect-news"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Read Gentoo eselect news in Emacs"

HOMEPAGE="https://github.com/marcin/emacs-eselect-news"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
