# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="eglot-python-preset"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Eglot preset for Python"

HOMEPAGE="https://github.com/mwolson/eglot-python-preset"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/eglot"
RDEPEND="app-emacs/eglot"
