# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="phony"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Define voice commands"

HOMEPAGE="https://github.com/ErikPrantare/phony.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/simulacrum"
RDEPEND="app-emacs/simulacrum"
