# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="card-games"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Play card games in Emacs (console UNICODE and graphical SVG)"

HOMEPAGE="https://code.bru.st/corwin/card-game.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
