# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="markdown-table-wrap"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Word-wrap GFM pipe tables to fit window width"

HOMEPAGE="https://github.com/dnouri/markdown-table-wrap"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
