# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="blamee"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Chunked git-blame overlays with popup details"

HOMEPAGE="https://github.com/fvi-att/blamee"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
