# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="outline-stars"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Outshine-style star headings for outline-minor-mode"

HOMEPAGE="https://codeberg.org/phmcc/outline-stars"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
