# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="simulacrum"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Inject custom event types into the event stream"

HOMEPAGE="https://github.com/ErikPrantare/simulacrum.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
