# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="consult-symbol"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Consult-based symbol search with narrowing"

HOMEPAGE="https://github.com/danielfleischer/consult-symbol"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/consult"
RDEPEND="app-emacs/consult"
