# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="ol-locate-file"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Locate-based file links for Org mode"

HOMEPAGE="https://github.com/p-snow/ol-locate-file"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/org-mode"
RDEPEND="app-emacs/org-mode"
