# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="aqui"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Location update (optimized for macOS)"

HOMEPAGE="https://github.com/kickingvegas/aqui"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/restlib"
RDEPEND="app-emacs/restlib"
