# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="rimel"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="A lightweight Rime input method"

HOMEPAGE="https://github.com/jixiuf/rimel"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/liberime"
RDEPEND="app-emacs/liberime"
