# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="latex-to-svg-frontend"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Preview LaTeX math in markup buffers as SVG"

HOMEPAGE="https://github.com/alberti42/latex-to-svg"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/latex-to-svg-backend"
RDEPEND="app-emacs/latex-to-svg-backend"
