# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="elfeed-protocol-freshrss"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="FreshRSS protocol for elfeed"

HOMEPAGE="https://codeberg.org/lou/elfeed-protocol-freshrss"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/elfeed
	app-emacs/elfeed-protocol
	app-emacs/deferred
	app-emacs/request
	app-emacs/request-deferred"
RDEPEND="app-emacs/elfeed
	app-emacs/elfeed-protocol
	app-emacs/deferred
	app-emacs/request
	app-emacs/request-deferred"
